version: "3.8"

services:
  db:
    image: postgres
    container_name: db-forlav
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    restart: always
      
  app:
    build: .
    container_name: rails-forlav
    environment:
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: password
    command: > 
      bash -c "rm -f tmp/pids/server.pid 
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on: 
      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
volumes:
  db:
