name: Ci desafio
on: push

env:
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  ENV: test

jobs: 
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}

    steps:
      - uses: actions/checkout@v1
      - name: set up ruby 
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: run tests
        env: 
          PG_USER: ${{env.POSTGRES_USER}}
          PG_HOST: ${{env.POSTGRES_HOST}}
          PG_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          RAILS_ENV: ${{env.ENV}}
        run: |
          bundle exec rails db:setup
          rspec

