name: Ci desafio
on: push

env:
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

jobs: 
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
              
    steps:
      - uses: actions/checkout@v1
      - name: set up ruby 
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: run tests
        env: 
          PG_USER: postgres
          PG_HOST: db
          PG_PASSWORD: password
          RAILS_ENV: test
        run: rspec

